"""targetgroup_and_errorhandling

Revision ID: 06a9c75f6dd9
Revises: eada4c9d0f5c
Create Date: 2020-05-12 15:45:35.215906

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '06a9c75f6dd9'
down_revision = 'eada4c9d0f5c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("initiative_imports") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.add_column(sa.Column('error_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('targetgroup', sa.String(length=250), nullable=True))
        # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("initiative_imports") as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_column('targetgroup')
        batch_op.drop_column('error_reason')
        # ### end Alembic commands ###
