"""Added extra import fields

Revision ID: 15e6476c5149
Revises: 90b88f0e6556
Create Date: 2020-04-25 16:27:57.580274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e6476c5149'
down_revision = '90b88f0e6556'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("initiatives") as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extra_fields', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('organiser', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source_uri', sa.String(length=500), server_default='http://unknown.org', nullable=False))
        batch_op.add_column(sa.Column('state', sa.Enum('imported', 'processed', 'processing_error'), server_default='imported', nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("initiatives") as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_column('url')
        batch_op.drop_column('state')
        batch_op.drop_column('source_uri')
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('organiser')
        batch_op.drop_column('extra_info')
        batch_op.drop_column('extra_fields')
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
