"""Rename initiatives

Revision ID: 431c7429cf6a
Revises: 15e6476c5149
Create Date: 2020-04-25 16:37:39.635991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431c7429cf6a'
down_revision = '15e6476c5149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table("initiatives") as batch_op:
    #    batch_op.
    op.rename_table('initiatives', 'initiative_imports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('initiative_imports', 'initiatives')
    # ### end Alembic commands ###
