"""Initial initiatives table

Revision ID: 90b88f0e6556
Revises: 
Create Date: 2020-04-25 15:05:36.972854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b88f0e6556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('group', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=True),
    sa.Column('source_id', sa.String(length=250), nullable=True),
    sa.Column('frequency', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('osm_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initiatives')
    # ### end Alembic commands ###
