"""batch and initiative tables

Revision ID: eada4c9d0f5c
Revises: 431c7429cf6a
Create Date: 2020-04-25 16:46:59.184031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eada4c9d0f5c'
down_revision = '431c7429cf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importbatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('running', 'imported', 'failed', 'processed', 'processing_error', name="initiatives_state_enum", native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("initiative_imports") as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('batch_fk', 'importbatches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("initiative_imports") as batch_op:
        batch_op.drop_constraint('batch_fk', type_='foreignkey')
        batch_op.drop_column('batch_id')
    op.drop_table('importbatches')
    op.drop_table('platforms')
    op.drop_table('initiatives')
    # ### end Alembic commands ###
