from .database import Initiative, Db


class Zorgheldenauto:
    """A simple example class"""

    zorgheldenautos = [
        'Auto Moret',
        'ABD Groep',
        'Auto Herwers',
        'Auto Indumij',
        'Auto Kievit',
        'Auto Munsterhuis',
        'Autobedrijf Hans Jongerius',
        'Autobedrijf Nieuwendijk',
        'ALD Automotive',
        'Autobedrijf Oving',
        'ASN Autoschade Roelofs',
        'Autobedrijf van de Wouw',
        'A-Point',
        'Autohopper',
        'Autohopper de Voogd',
        'Autohopper Maastricht',
        'Autohopper Zevenbergen',
        'Autohopper Weert',
        'Athlon Nederland',
        'Avis Budget Group',
        'Autobedrijf van Tilborg',
        'Autop autoverhuur',
        'Auto Indumij',
        'Auto Huiskes',
        'Auto Romme',
        'Autoservice Menges & de Vries',
        'Autobedrijf van de Wouw',
        'Ad Alliance',
        'Avitas Autolease',
        'Autoservice de Ambacht',
        'Benderooy.nl',
        'Blauwendaal',
        'Bedrijfswagen Centrum HW',
        'BNA Bureau Notariaat en Advocatuur BV',
        'Blokweg',
        'Bochane',
        'Bliss4Media',
        'Chris Bergström',
        'Captcha!',
        'de Korte projectmanagement',
        'Domien Verschuuren',
        'Drive Amber',
        'Diks Autoverhuur',
        'DPG',
        'De Autofinancier',
        'Easyrent',
        'Ekris BMW en MINI ',
        'Euromobil',
        'Ellens Investments', 
        'Freeroad',
        'Geerts Cleaning Service',
        'Goldcar',
        'Greven bedrijfswagens',
        'Exact Groep',
        'Exterion Media',
        'Finalease',
        'Flitsmeister',
        'Fetch car sharing',
        'Freeroad',
        'Hertz',
        'H4 Lease Hardinxveld',
        'H4 Lease Deventer',
        'Hitachi Capital Mobility',
        'Hyundai Motor Nederland',
        'Hylkema Peugeot',
        'Indulease',
        'Impact Personeel',
        'Inqar',
        'Janssen Kerres',
        'Logicx',
        'Lexus Nederland',
        'Louwman Amsterdam',
        'Louwman Brabant',
        'Louwman Groningen',
        'Louwman Haaglanden',
        'Louwman Rijnmond',
        'Leaselinq',
        'Mannenmedia',
        'Mundu',
        'Mediahuis',
        'Massarius',
        'Mazda Motor Nederland',
        'M. de Koning Autoverhuur',
        'Marktplaats',
        'MisterGreen Electric Lease',
        'Nefkens Noord',
        'NRC',
        'NDC mediagroep',
        'OMS',
        'Qmusic',
        'Renault Nederland',
        '100% NL',
        'QnQ Engineering',
        'Rüttchen Automotive',
        'Reflecta Automation',
        'Shell. Sip Hibma',
        'Setz Autoverhuur',
        'Supershortlease',
        'SIXT',
        'Select Car Lease',
        'Stern',
        'Stokman Alkmaar',
        'Segerink & Wolbers',
        'Siton Engelsma Wijnia Deinum Opel Nissan',
        'Suzuki Nederland',
        'Trekhaakcentrum.nl',
        'Talpa',
        'TB Autoverhuur',
        'Toyota Van Haasteren Motors',
        'Telstar Print',
        'Volkswagen Pon Financial Services en DFM',
        'Van Mossel VKV',
        'Vakgarage SDH',
        'Wavemaker Nederland',
        'Wittebrug',
        'WDM Autoverhuur',
        'Wim Vonk',
        'Welzorg',
        'Zeeuw & Zeeuw',
    ]

    def scrape(self):
        db = Db()
        for company in self.zorgheldenautos:
            db.session.add(Initiative(name=company,
                                      group="zorgheldenauto",
                                      source='https://www.auto.nl/zorgheldenauto',
                                      )
                           )

        db.session.commit()
